name: 🐛 Bug Report
description: Report a problem with Zotero Citation Linker
title: "[Bug]: "
labels:
  - bug
  - needs-triage

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-flight checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I am using the latest version of the plugin
          required: true
        - label: I have restarted Zotero after installing/updating the plugin
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Tell us how to reproduce this issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected outcome
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened?
      placeholder: Describe what went wrong
    validations:
      required: true

  - type: dropdown
    id: zotero-version
    attributes:
      label: 📚 Zotero Version
      description: Which version of Zotero are you using?
      options:
        - "7.0.x (latest)"
        - "6.0.x (legacy)"
        - "Other (please specify in additional context)"
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: 🔧 Plugin Version
      description: Which version of Zotero Citation Linker?
      placeholder: "e.g., 1.1.0"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: 💻 Operating System
      description: Which OS are you using?
      options:
        - "Windows 11"
        - "Windows 10"
        - "macOS (latest)"
        - "macOS (older version)"
        - "Linux (Ubuntu/Debian)"
        - "Linux (other)"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: 📋 Error Logs
      description: |
        Please include any error messages from:
        - Zotero Error Console (Help → Debug Output Logging → Submit to Zotero)
        - Browser Developer Console (if using HTTP server)
      placeholder: Paste error logs here
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: |
        Add any other context about the problem:
        - Screenshots or videos
        - Related plugins or configurations
        - Workarounds you've tried
      placeholder: Any additional information that might help...
